export const QUERY_ARTIST = 'QUERY_ARTIST';
export const QUERY_ARTIST_SUCCESS = 'QUERY_ARTIST_SUCCESS';
export const QUERY_ARTIST_ERROR = 'QUERY_ARTIST_ERROR';

export const QUERY_ARTIST_EVENT = 'QUERY_ARTIST_EVENT';
export const QUERY_ARTIST_EVENT_SUCCESS = 'QUERY_ARTIST_EVENT_SUCCESS';
export const QUERY_ARTIST_EVENT_ERROR = 'QUERY_ARTIST_EVENT_ERROR';

export const QUERY_ARTIST_NAME = 'QUERY_ARTIST_NAME';
export const QUERY_ARTIST_NAME_SUCCESS = 'QUERY_ARTIST_NAME_SUCCESS';
export const QUERY_ARTIST_NAME_ERROR = 'QUERY_ARTIST_NAME_ERROR';
